NETWORK:
  WIDTH_FACTOR: 1.0
  DEPTH_FACTOR: 5.0
  BOTTLENECK_WIDTH_FACTOR: 2.25
  C1_CHANNELS: 12
  NUM_CLASSES: 400
  DROPOUT_RATE: 0.5
  MIXED_PRECISION: True
  BN:
    MOMENTUM: 0.9
    EPS: 1e-5
DATA:
  FRAME_RATE: 5
  TEMP_DURATION: 16
  NUM_INPUT_CHANNELS: 3
  MEAN: [0.433, 0.404, 0.377] # see https://github.com/kkahatapitiya/X3D-Multigrid/blob/master/train_x3d_kinetics_multigrid.py#L46
  STD: [0.151, 0.148, 0.157]
  TRAIN_JITTER_SCALES: [356, 446]
  TRAIN_CROP_SIZE: 312
  TEST_CROP_SIZE: 312 # use if TEST.NUM_SPATIAL_CROPS: 1
  # TEST_CROP_SIZE: 356 # use if TEST.NUM_SPATIAL_CROPS: 3
  TRAIN_LABEL_PATH: "dataset/kinetics400/train.txt"
  TEST_LABEL_PATH: "dataset/kinetics400/val.txt"
TRAIN:
  DATASET_SIZE: 234619
  BATCH_SIZE: 4
  EPOCHS: 200
  MULTI_GPU: True
  MODEL_DIR: "trial/L"
  OPTIMIZER: "SGD" # supports sgd or adam
  BASE_LR: 0.1
  WARMUP_EPOCHS: 25
  WARMUP_LR: 0.01
  MOMENTUM: 0.9
  SAVE_CHECKPOINTS_EVERY: 1000
TEST:
  NUM_SPATIAL_CROPS: 3
  NUM_TEMPORAL_VIEWS: 1
  DATASET_SIZE: 19761
  BATCH_SIZE: 4
WANDB:
  ENABLE: True
  PROJECT_NAME: "X3D-tf"
  GROUP_NAME: "X3D-L"
  MODE: "online"
  TENSORBOARD: True