NETWORK:
  WIDTH_FACTOR: 1.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_WIDTH_FACTOR: 2.25
  C1_CHANNELS: 12
  NUM_CLASSES: 400
  DROPOUT_RATE: 0.5
  BN:
    MOMENTUM: 0.9
    EPS: 1e-5
DATA:
  FRAME_RATE: 12
  TEMP_DURATION: 4
  NUM_INPUT_CHANNELS: 3
  MEAN: [0.433, 0.404, 0.377] # see https://github.com/kkahatapitiya/X3D-Multigrid/blob/master/train_x3d_kinetics_multigrid.py#L46
  STD: [0.151, 0.148, 0.157]
  TRAIN_JITTER_SCALES: [182, 228]
  TRAIN_CROP_SIZE: 160
  TEST_CROP_SIZE: 160
  #TEST_CROP_SIZE: 182 # use if TEST.NUM_SPATIAL_CROPS: 3
TRAIN:
  DATASET_SIZE: 234619
  BATCH_SIZE: 128
  EPOCHS: 300
  OPTIMIZER: sgd # supports sgd or adam
  BASE_LR: 0.8
  WARMUP_EPOCHS: 35
  WARMUP_LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TEST:
  NUM_SPATIAL_CROPS: 1
  NUM_TEMPORAL_VIEWS: 10
  DATASET_SIZE: 19761
  BATCH_SIZE: 16
WANDB:
  ENABLE: True
  PROJECT_NAME: X3D-tf
  GROUP_NAME: X3D-XS
  MODE: online
  TENSORBOARD: True

