NETWORK:
  WIDTH_FACTOR: 1.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_WIDTH_FACTOR: 2.25
  C1_CHANNELS: 12
  NUM_CLASSES: 400
  DROPOUT_RATE: 0.5
  MIXED_PRECISION: False
  BN:
    MOMENTUM: 0.9
    EPS: 1e-5
DATA:
  FRAME_RATE: 5
  TEMP_DURATION: 16
  NUM_INPUT_CHANNELS: 3
  TRAIN_JITTER_SCALES: [256, 320]
  MEAN: [0.433, 0.404, 0.377] # see https://github.com/kkahatapitiya/X3D-Multigrid/blob/master/train_x3d_kinetics_multigrid.py#L46
  STD: [0.151, 0.148, 0.157]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  #TEST_CROP_SIZE: 256 # use if TEST.NUM_SPATIAL_CROPS: 3
  TRAIN_LABEL_PATH: "dataset/kinetics400/train.txt"
  TEST_LABEL_PATH: "dataset/kinetics400/val.txt"
TRAIN:
  DATASET_SIZE: 234619
  BATCH_SIZE: 64
  EPOCHS: 100
  MULTI_GPU: True
  NUM_GPUS: 8
  MODEL_DIR: "ckpts/X3D-M"
  OPTIMIZER: "SGD" # supports sgd or adam
  BASE_LR: 0.2
  WARMUP_EPOCHS: 10
  WARMUP_LR: 0.02
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.00005
  SAVE_CHECKPOINTS_EVERY: 1000
TEST:
  NUM_SPATIAL_CROPS: 1
  NUM_TEMPORAL_VIEWS: 10
  DATASET_SIZE: 19761
  BATCH_SIZE: 8
WANDB:
  ENABLE: True
  PROJECT_NAME: "X3D-tf"
  GROUP_NAME: "X3D-M"
  MODE: "online"
  TENSORBOARD: True
