NETWORK:
  WIDTH_FACTOR: 1.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_WIDTH_FACTOR: 2.25
  C1_CHANNELS: 12
  NUM_CLASSES: 400
  DROPOUT_RATE: 0.5
  MIXED_PRECISION: True
  BN:
    MOMENTUM: 0.9
    EPS: 1e-5
DATA:
  FRAME_RATE: 5
  TEMP_DURATION: 16
  NUM_INPUT_CHANNELS: 3
  TRAIN_JITTER_SCALES: [256, 320]
  MEAN: [0.433, 0.404, 0.377] # see https://github.com/kkahatapitiya/X3D-Multigrid/blob/master/train_x3d_kinetics_multigrid.py#L46
  STD: [0.151, 0.148, 0.157]
  TRAIN_CROP_SIZE: 224
  #TEST_CROP_SIZE: 224 # use if TEST.NUM_SPATIAL_CROPS: 1
  TEST_CROP_SIZE: 256 # use if TEST.NUM_SPATIAL_CROPS: 3
  TRAIN_LABEL_PATH: "dataset/kinetics400/train.txt"
  TEST_LABEL_PATH: "dataset/kinetics400/val.txt"
TRAIN:
  DATASET_SIZE: 234619
  BATCH_SIZE: 4
  EPOCHS: 200
  MULTI_GPU: True
  MODEL_DIR: "trial/M"
TEST:
  NUM_SPATIAL_CROPS: 3
  NUM_TEMPORAL_VIEWS: 1
  DATASET_SIZE: 19761
  BATCH_SIZE: 4