NETWORK:
  WIDTH_FACTOR: 1.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_WIDTH_FACTOR: 2.25
  C1_CHANNELS: 12
  NUM_CLASSES: 400
  DROPOUT_RATE: 0.5
  BN:
    MOMENTUM: 0.9
    EPS: 1e-5
DATA:
  FRAME_RATE: 6
  TEMP_DURATION: 13
  NUM_INPUT_CHANNELS: 3
  SPATIAL_RES: 160
