NETWORK:
  WIDTH_FACTOR: 2.9
  DEPTH_FACTOR: 5.0
  BOTTLENECK_WIDTH_FACTOR: 2.25
  C1_CHANNELS: 12
  SCALE_RES2: True
  NUM_CLASSES: 400
  DROPOUT_RATE: 0.5
  BN:
    MOMENTUM: 0.9
    EPS: 1e-5
DATA:
  FRAME_RATE: 5
  TEMP_DURATION: 16
  NUM_INPUT_CHANNELS: 3
  SPATIAL_RES: 312
